name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.event_name == 'release'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name == 'release' }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/temp-file-api:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/temp-file-api:${{ github.sha }}
            ${{ github.event_name == 'release' && format('{0}/temp-file-api:{1}', secrets.DOCKER_HUB_USERNAME, github.ref_name) || '' }}
